### ISSUE TITLE
Debugger fails to run complaining it cannot find the executable though the file is there; ST3

### ISSUE THREAD

**Issue by eugenio** [daveleroy/sublime_debugger#113]
On sublime text 3 the debugger installs just fine including the adapter but when I try to run it it fails with the console output below:

``` Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1050, in run_
    return self.run(**args)
TypeError: run() got an unexpected keyword argument 'list_1'
Starting process: ['node', 'C:\\Users\\eugen\\AppData\\Roaming\\Sublime Text 3\\Packages\\Debugger/debug_adapters/lldb_util/entry.js', 'C:\\Users\\eugen\\AppData\\Roaming\\Sublime Text 3\\Packages\\Debugger\\data\\debug_adapters\\vscode-lldb/extension/adapter/codelldb']
Traceback (most recent call last):
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\core\sublime_event_loop.py", line 13, in __call__
    self.callback(*self.args)
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\core\core.py", line 54, in done
    result = task.result()
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 293, in result
    raise self._exception
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\debugger\debugger_session.py", line 207, in _launch
    yield from adapter.Launch(configuration.all, restart, no_debug)
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\dap\client.py", line 254, in Launch
    yield from self.send_request_asyc('launch', config)
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\coroutines.py", line 213, in coro
    res = yield from res
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\tasks.py", line 304, in _wakeup
    future.result()
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 293, in result
    raise self._exception
Debugger.modules.dap.types.Error: unable to find executable for 'C:\Users\eugen\OneDrive\Documenti\programmazione\rust\kicad-rs\target\debug\kicad-rs.exe'
unable to find executable for 'C:\Users\eugen\OneDrive\Documenti\programmazione\rust\kicad-rs\target\debug\kicad-rs.exe'Traceback (most recent call last):
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\debugger\debugger_session.py", line 121, in launch
    yield from self.launching_async
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\tasks.py", line 304, in _wakeup
    future.result()
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 293, in result
    raise self._exception
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\core\sublime_event_loop.py", line 13, in __call__
    self.callback(*self.args)
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\core\core.py", line 54, in done
    result = task.result()
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 293, in result
    raise self._exception
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\debugger\debugger_session.py", line 207, in _launch
    yield from adapter.Launch(configuration.all, restart, no_debug)
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\dap\client.py", line 254, in Launch
    yield from self.send_request_asyc('launch', config)
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\coroutines.py", line 213, in coro
    res = yield from res
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\tasks.py", line 304, in _wakeup
    future.result()
  File "C:\Users\eugen\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 293, in result
    raise self._exception
Debugger.modules.dap.types.Error: unable to find executable for 'C:\Users\eugen\OneDrive\Documenti\programmazione\rust\kicad-rs\target\debug\kicad-rs.exe'

disposing Debugger
Debug Adapter process was terminated prematurely
Settings were udpdated: reloading configuations
```
this below is my sublime project file:

```
{
	"folders":
	[
		{
			"path": "C:/Users/eugen/OneDrive/Documenti/programmazione/rust/kicad-rs"
		}
	],
	"settings":
	{
		"debug.configurations":
		[

			{
                "name": "Debug",
                "type": "lldb", 
                "request": "launch", 
                "program": "${workspaceFolder}/../target/debug/kicad-rs",
                "sourceMap": {"" : "C:/Users/eugen/.rustup/toolchains/nightly-x86_64-pc-windows-msvc/lib/rustlib/src/rust"}
            },

		]
	}
}
```

could anyone please help me to solve this?

**Comment by eugenio** [comment]
I was completely my fault as the project name and the executable name have slightly different spelling. Now it works properly!
