### ISSUE TITLE
Mac OS - LLDB terminal broken

### ISSUE THREAD

**Issue by MrStevns** [daveleroy/sublime_debugger#114]
Hi

I'm having trouble launching the terminal when stating the debugger on master branch. The log complains about PtyProcess module not found.

it works in the latest release (0.4.1).

I've tried to backtrace where the problem would have been introduced but it's not easy...
After commit 729affe0d2bc8135dd57138c94e969bdd119153b the debugger panel doesn't work at all and the latest commit where i'm able to see the debugger panel 9db03240f8c1cde559c586cc24f03bc48f0e4f46 the terminal is broken.

```
Traceback (most recent call last):
  File "/Users/candyface/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/core/sublime_event_loop.py", line 105, in call_exception_handler
    raise context['exception']
  File "/Users/candyface/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/dap/transport.py", line 189, in handle_reverse_request
    response = await self.events.on_reverse_request(command, request.get('arguments', {}))
  File "/Users/candyface/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/dap/session.py", line 692, in on_reverse_request
    response = await self.on_run_in_terminal(dap.RunInTerminalRequest.from_json(arguments))
  File "/Users/candyface/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/dap/session.py", line 704, in on_run_in_terminal
    return await self.listener.on_session_terminal_request(self, request)
  File "/Users/candyface/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/dap/sessions.py", line 65, in on_session_terminal_request
    await self.provider.sessions_create_terminal(session, request)
  File "/Users/candyface/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/debugger.py", line 548, in sessions_create_terminal
    terminal = TerminalProcess(request.cwd, request.args)
  File "/Users/candyface/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/terminal_process.py", line 82, in __init__
    self.process = TtyProcess(args, on_output=self.on_process_output, cwd=cwd)
  File "/Users/candyface/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/terminal_process.py", line 32, in __init__
    self.process = PtyProcess.spawn(command, cwd=cwd)
NameError: name 'PtyProcess' is not defined
```

My Specs:
MacBook Pro (Retina, 13-inch, Early 2015)
Mac OS 10.15.6
Sublime Text 4: 4107

**Comment by daveleroy** [comment]
No dependencies work on st4 so the integrated terminal will not work at the moment. I am working on vendering these dependencies but I don't have a windows or linux setup with me.

Specifying `terminal: console` will make it not use the integrated terminal.

**Comment by CandyFace** [comment]
Ah good to know! I recall reading that somewhere in the code...

I've specified that it should use console now but nothing changes. 
What is the difference between terminal and external_terminal?

My config looks like this:
```

{
	"lldb.show_disassembly": "auto",
	"external_terminal": "terminus",
	"terminal": "console"
}

```

I have also tried using external_terminal: platform but it doesn't change the outcome. It still complains about ptyprocess in the console.
What would the expected behaviour be here?

**Comment by daveleroy** [comment]
Sorry I meant in the configuration for the debugger session.

```
{
	"name": "Test",
	"type": "lldb",
	"request": "launch",
	"program": "${project_path}/test",
	"cwd": "${project_path}",
	"terminal": "console",
}
```

The mapping to what terminal to use is driven by the debug adapter so not all adapters have the same "terminal" settings. The adapters can either not use a terminal at all ("console" in lldb) output goes to the "Debugger Console" tab, use the integrated terminal which is the terminal tab ("integrated" in lldb) or use the external terminal ("external" in lldb).

If an external terminal is requested then what terminal to use is dictated by the "external_terminal" setting in Debugger Settings. Currently the support is limited and probably only terminus actually works at the moment (requires https://github.com/randy3k/Terminus).
