### ISSUE TITLE
debugger fails to start - help further debugging that

### ISSUE THREAD

**Issue by nacho319** [daveleroy/sublime_debugger#128]
I'm not sure where else to Google/DuckDuckGo my problems or what other logging, etc. to turn on.  I'm trying to get the LLDB (but GDB would be fine too) debug adapter to work on some C code.  I get this in the debugger console log:

```
[2021-10-07T18:21:04.041Z ERROR codelldb::dap_codec] Could not deserialize: data did not match any variant of untagged enum ResponseResult

[2021-10-07T18:21:04.041Z ERROR codelldb::terminal] channel closed
[2021-10-07T18:21:04.041Z ERROR codelldb::debug_session] shared_session.ref_count=4
```

And in the Sublime console window I have this:

```
<Debugger.modules.dap.session.Session object at 0x104cd40d0>
Starting process: ['/Users/inacio/Library/Application Support/Sublime Text 3/Packages/Debugger/data/adapters/lldb/extension/adapter/codelldb', 'terminal-agent', '--port=52001']
Debugger: [2021-10-07T18:21:04.041Z ERROR codelldb::dap_codec] Could not deserialize: data did not match any variant of untagged enum ResponseResult

Debugger: [2021-10-07T18:21:04.041Z ERROR codelldb::terminal] channel closed
[2021-10-07T18:21:04.041Z ERROR codelldb::debug_session] shared_session.ref_count=4

<Future pending>
Traceback (most recent call last):
  File "/Users/inacio/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/core/sublime_event_loop.py", line 14, in __call__
    self.callback(*self.args)
  File "/Users/inacio/Library/Application Support/Sublime Text 3/Packages/Debugger/modules/core/core.py", line 58, in done
    exception = task.exception() 
asyncio.exceptions.CancelledError
Debugger: Nothing to read from process, closing
finished
```

and my debugger configuration looks like:

```
	"debugger_configurations":
	[
		{
			"name": "LLDB PrettyKate",
			"type": "lldb",
			"request": "launch",
			"program": "${workspaceFolder}/src/prettyKate",
			"args": ["-c", "${workspaceFolder}/tests/unimplementedFunc.lua"],
		},
		{
			"name": "PrettyKate GDB",
			"type": "gdb",
			"request": "launch",
			"program": "${workspaceFolder}/src/prettyKate",
			"args": ["-c", "${workspaceFolder}/tests/unimplementedFunc.lua"],
		}
	],
```

and my debugger.sublime-settings:

```
//{
//      "adapters_custom" : {
//              "ggdb" : {
//                      "/opt/local/bin/ggdb" : ["p", "-arg"]
//              }
//      }
//}
{
        "lldb.show_disassembly": "auto",
        "font_face": "Fira Code",
        "log_info": true,
        "should_log_info": true,
}
```

I did do the test of getting this configuration to work on VSCode with the only change being `${workspaceFolder}` to be the absolute path.  That didn't change anything in Sublime when I tried it.  I have Sublime 4113 installed if that matters.  I'm fine with trying to debug this more, but I'm not sure where to look.  Adding `should_log_info` came from reading these open bugs.  I hope this is the place to put this, I couldn't find a forum, etc. to ask in.

**Comment by daveleroy** [comment]
Oh I see the issue the problem. For now adding `"terminal": "console",` to your configuration should fix the issue.

**Comment by nacho319** [comment]
First, thank you, that fixed it.

Just so that this is complete, if other people manage to find it:

vscode-lldb version is 1.6.7
MacOS 11.6

I'll try to get 1.6.8 installed ASAP.  It doesn't want to try behind the corporate firewall…
