### ISSUE TITLE
install fail

### ISSUE THREAD

**Issue by AmjadHD** [daveleroy/sublime_debugger#13]
```https://marketplace.visualstudio.com/_apis/public/gallery/publishers/felixfbecker/vsextensions/php-debug/latest/vspackage
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/msjsdiag/vsextensions/debugger-for-chrome/latest/vspackage
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/latest/vspackage
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\sublime_db\main\commands.py", line 180, in install
    self.download(cfg)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\sublime_db\main\commands.py", line 152, in download
    shutil.copyfileobj(response, out_file)
  File "./python3.3/shutil.py", line 68, in copyfileobj
  File "./python3.3/gzip.py", line 367, in read
  File "./python3.3/gzip.py", line 456, in _read
  File "./python3.3/gzip.py", line 488, in _read_eof
  File "./python3.3/gzip.py", line 69, in read32
struct.error: unpack requires a bytes object of length 4
```
os: windows

**Comment by klmp200** [comment]
Maybe visualstudio.com is sending a diffrent kind of archive for windows users, I'm gonna investigate.

**Comment by daveleroy** [comment]
I believe the response is probably encoded differently for him. I added the header "Accept-Encoding" : "gzip" and only run gzip on it if the response has "Content-Encoding" : "gzip" set. 

I tested on windows it was working for me (The previous version was too however)

**Comment by AmjadHD** [comment]
since the problem is unpacking the archive, I unpacked it manually using 7-zip and it worked (using winrar however didn't).
