### ISSUE TITLE
[Question]: Console is in 'commands' mode, prefix expressions with '?'.

### ISSUE THREAD

**Issue by danielTobon43** [daveleroy/sublime_debugger#161]
Hi @daveleroy.

Greetings.

I have installed the sublime_debbuger to use it with a c++ application and I have followed all the steps according to the documentation, but after I set a breakpoint and hit the play button, I got this error in the console.

![Screenshot from 2022-05-20 07-19-36](https://user-images.githubusercontent.com/35694200/169526764-976a0907-7cb7-492a-82ce-2ed3f52c35fe.png)

![Screenshot from 2022-05-20 07-21-42](https://user-images.githubusercontent.com/35694200/169527090-aa93547c-3297-4cf9-abff-181d3981ed7a.png)

Do you know what might be wrong?

**Possible solution**:
- I have changed "terminal": "console" (not working)

**My environment:**

Linux Ubuntu 20.04
Sublime text 4
Project compiled with cmake/make

**Console log**

```
--
Starting process: ['/home/danieltc/.config/sublime-text-3/Packages/Debugger/data/adapters/lldb/extension/adapter/codelldb', 'terminal-agent', '--connect=34885']
Traceback (most recent call last):
  File "/home/danieltc/.config/sublime-text-3/Packages/Debugger/modules/core/sublime_event_loop.py", line 13, in __call__
    self.callback(*self.args)
  File "/home/danieltc/.config/sublime-text-3/Packages/Debugger/modules/core/core.py", line 79, in done
    result: T = task.result()
  File "/home/danieltc/.config/sublime-text-3/Packages/Debugger/modules/dap/session.py", line 217, in _launch
    await self.request('launch', self.configuration)
  File "/home/danieltc/.config/sublime-text-3/Packages/Debugger/modules/dap/session.py", line 238, in request
    return await self._transport.send_request_asyc(command, arguments)
Debugger.modules.dap.error.Error: 'A' packet returned an error: 8
Debugger: 'A' packet returned an error: 8Traceback (most recent call last):
  File "/home/danieltc/.config/sublime-text-3/Packages/Debugger/modules/dap/session.py", line 154, in launch
    await self.launching_async
  File "/home/danieltc/.config/sublime-text-3/Packages/Debugger/modules/core/sublime_event_loop.py", line 13, in __call__
    self.callback(*self.args)
  File "/home/danieltc/.config/sublime-text-3/Packages/Debugger/modules/core/core.py", line 79, in done
    result: T = task.result()
  File "/home/danieltc/.config/sublime-text-3/Packages/Debugger/modules/dap/session.py", line 217, in _launch
    await self.request('launch', self.configuration)
  File "/home/danieltc/.config/sublime-text-3/Packages/Debugger/modules/dap/session.py", line 238, in request
    return await self._transport.send_request_asyc(command, arguments)
Debugger.modules.dap.error.Error: 'A' packet returned an error: 8

--
```

**Comment by danielTobon43** [comment]
I found out that I have compiled the binary file in a 32bit architecture. I have recompiled it the bin file in my current system but, now I am getting a new error:

```
Debugger: ProjectConfiguration.reload
Starting process: ['/home/danieltc/.config/sublime-text-3/Packages/Debugger/data/adapters/lldb/extension/adapter/codelldb', 'terminal-agent', '--connect=35887']
Debugger: error: event ignored not implemented exited
```

**Comment by danielTobon43** [comment]
The vscode debugger is working properly with my project, so I think I am going to stick for a while with vscode.

Thanks!
