### ISSUE TITLE
Trying to get Camel Debugger work

### ISSUE THREAD

**Issue by Navyashree0923** [daveleroy/sublime_debugger#187]
Hello,

I want to run Camel debugger with [Camel-Debug ](https://github.com/camel-tooling/camel-debug-adapter#debug-adapter-for-apache-camel),

This is the content  of my `camel.py` file  :
```
from __future__ import annotations
from ..typecheck import *

from .import util
from .. import dap
from .. import core

import sublime
import re

class Camel(dap.AdapterConfiguration):

    type = 'camel'
    docs = 'https://github.com/camel-tooling/camel-debug-adapter#debug-adapter-for-apache-camel'

    installer = util.OpenVsxInstaller (
        type='camel',
        repo='redhat/vscode-debug-adapter-apache-camel'
    )

    async def start(self, log: core.Logger, configuration: dap.ConfigurationExpanded):

        install_path = util.vscode.install_path(self.type)
        command = [
            'java',
            '-jar'
            f'{install_path}/extension/jars/camel-dap-server.jar'
        ]
        return dap.StdioTransport(log, command)
```
This is the content of my `camel.sublime-project` file : 
```
{
	"folders":
	[
		{
			"path": ".",
		}
	],
	"debugger_configurations":
	[
	
		{
			"type": "camel",
			"request": "attach",
			"name": "Attach to Camel Debugger",
		}
	],
}
```
I'm able to start the program but when I start debugging, the debugger console shows nothing.
Could you please me understand how should I proceed further on this issue?
Thanks in advance

**Comment by daveleroy** [comment]
Look in `Debugger: Show Protocol` and see what is being passed to/from the adapter

**Comment by Navyashree0923** [comment]
I can see this in `Debugger: Show Protocol`
```
process/starting :: ['java', '-jar/home/npr/.config/sublime-text/Packages/Debugger/data/adapters/camel/extension/jars/camel-dap-server.jar']
⟸ process/started ::
⟸ request/initialize(1) :: {'clientID': 'sublime', 'clientName': 'Sublime Text', 'adapterID': 'camel', 'pathFormat': 'path', 'linesStartAt1': True, 'columnsStartAt1': True, 'supportsVariableType': True, 'supportsVariablePaging': False, 'supportsRunInTerminalRequest': True, 'supportsMemoryReferences': True, 'locale': 'en-us'}
⟸ process/stderr :: Unrecognized option: -jar/home/npr/.config/sublime-text/Packages/Debugger/data/adapters/camel/extension/jars/camel-dap-server.jar
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

⟸ process/stopped :: 
```

**Comment by daveleroy** [comment]
I think you are missing a `,` after `'-jar'` and python thinks its a good idea to just concatenate the strings I guess

**Comment by Navyashree0923** [comment]
Sorry my bad. I missed the `,` there but now I see some exceptions in the `Debugger : show Protocol` tab :
```
⟸ process/starting :: ['java', '-jar', '/home/npr/.config/sublime-text/Packages/Debugger/data/adapters/camel/extension/jars/camel-dap-server.jar']
⟸ process/started ::
⟸ request/initialize(1) :: {'clientID': 'sublime', 'clientName': 'Sublime Text', 'adapterID': 'camel', 'pathFormat': 'path', 'linesStartAt1': True, 'columnsStartAt1': True, 'supportsVariableType': True, 'supportsVariablePaging': False, 'supportsRunInTerminalRequest': True, 'supportsMemoryReferences': True, 'locale': 'en-us'}
⟸ process/stopped :: 
⟹ response/initialize(1) :: {'supportsConfigurationDoneRequest': True, 'supportsConditionalBreakpoints': True, 'supportsSetVariable': True}
⟸ request/attach(2) :: {'name': 'Attach to Camel Debugger', 'request': 'attach', 'type': 'camel'}
⟸ request/evaluate(3) :: {'expression': 'file', 'context': 'hover', 'frameId': None}
⟸ process/stderr :: Oct 13, 2022 11:08:31 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.UnsupportedOperationException
	at org.eclipse.lsp4j.debug.services.IDebugProtocolServer.evaluate(IDebugProtocolServer.java:598)
	... 16 more


⟾ response/evaluate(3) :: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.UnsupportedOperationException
	at org.eclipse.lsp4j.debug.services.IDebugProtocolServer.evaluate(IDebugProtocolServer.java:598)
	... 16 more

⟸ request/evaluate(4) :: {'expression': 'Licensed', 'context': 'hover', 'frameId': None}
⟸ process/stderr :: Oct 13, 2022 11:10:24 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.UnsupportedOperationException
	at org.eclipse.lsp4j.debug.services.IDebugProtocolServer.evaluate(IDebugProtocolServer.java:598)
	... 16 more


⟾ response/evaluate(4) :: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.UnsupportedOperationException
	at org.eclipse.lsp4j.debug.services.IDebugProtocolServer.evaluate(IDebugProtocolServer.java:598)
	... 16 more
```
The Camel debug adapter server is working fine with Vimspector and emacs-dap but for some reason I'm seeing these errors when hitting the breakpoint.

**Comment by daveleroy** [comment]
This looks like an issue with the adapter which isn't sending a response to `attach`. The debugger is just waiting for the adapter here.

Those errors appear to be in response to hover evaluate requests and are probably unrelated if you don't hover over anything they wouldn't be triggering.

**Comment by Navyashree0923** [comment]
Oh ok. make sense. I see the following data from ` /tmp/log-camel-dap.log` file.
```


2022-10-13 22:51:49.886 WARN [ForkJoinPool.commonPool-worker-5] [com.github.cameltooling.dap.internal.CamelDebugAdapterServer.setBreakpointsSync(CamelDebugAdapterServer.java:162)] - No active routes find in Camel context. Consequently, cannot set breakpoint for /home/npr/camel-examples/examples/main/src/main/java/org/apache/camel/example/MyRouteBuilder.java l.29
2022-10-13 22:51:53.022 WARN [ForkJoinPool.commonPool-worker-5] [com.github.cameltooling.dap.internal.CamelDebugAdapterServer.setBreakpointsSync(CamelDebugAdapterServer.java:162)] - No active routes find in Camel context. Consequently, cannot set breakpoint for /home/npr/camel-examples/examples/main/src/main/java/org/apache/camel/example/MyRouteBuilder.java l.27
2022-10-13 22:51:53.022 WARN [ForkJoinPool.commonPool-worker-5] [com.github.cameltooling.dap.internal.CamelDebugAdapterServer.setBreakpointsSync(CamelDebugAdapterServer.java:162)] - No active routes find in Camel context. Consequently, cannot set breakpoint for /home/npr/camel-examples/examples/main/src/main/java/org/apache/camel/example/MyRouteBuilder.java l.29
2022-10-13 22:51:57.435 WARN [ForkJoinPool.commonPool-worker-5] [com.github.cameltooling.dap.internal.CamelDebugAdapterServer.setBreakpointsSync(CamelDebugAdapterServer.java:162)] - No active routes find in Camel context. Consequently, cannot set breakpoint for /home/npr/camel-examples/examples/main/src/main/java/org/apache/camel/example/MyRouteBuilder.java l.29
2022-10-13 22:51:59.467 WARN [ForkJoinPool.commonPool-worker-5] [com.github.cameltooling.dap.internal.CamelDebugAdapterServer.setBreakpointsSync(CamelDebugAdapterServer.java:162)] - No active routes find in Camel context. Consequently, cannot set breakpoint for /home/npr/camel-examples/examples/main/src/main/java/org/apache/camel/example/MyRouteBuilder.java l.27
2022-10-13 22:51:59.467 WARN [ForkJoinPool.commonPool-worker-5] [com.github.cameltooling.dap.internal.CamelDebugAdapterServer.setBreakpointsSync(CamelDebugAdapterServer.java:162)] - No active routes find in Camel context. Consequently, cannot set breakpoint for /home/npr/camel-examples/examples/main/src/main/java/org/apache/camel/example/MyRouteBuilder.java l.29
2022-10-13 22:52:01.244 WARN [ForkJoinPool.commonPool-worker-5] [com.github.cameltooling.dap.internal.CamelDebugAdapterServer.setBreakpointsSync(CamelDebugAdapterServer.java:162)] - No active routes find in Camel context. Consequently, cannot set breakpoint for /home/npr/camel-examples/examples/main/src/main/java/org/apache/camel/example/MyRouteBuilder.java l.29
2022-10-13 22:53:04.115 WARN [ForkJoinPool.commonPool-worker-5] [com.github.cameltooling.dap.internal.CamelDebugAdapterServer.setBreakpointsSync(CamelDebugAdapterServer.java:162)] - No active routes find in Camel context. Consequently, cannot set breakpoint for /home/npr/camel-examples/examples/main/src/main/java/org/apache/camel/example/MyRouteBuilder.java l.27
2022-10-13 22:53:19.040 WARN [ForkJoinPool.commonPool-worker-5] [com.github.cameltooling.dap.internal.CamelDebugAdapterServer.setBreakpointsSync(CamelDebugAdapterServer.java:162)] - No active routes find in Camel context. Consequently, cannot set breakpoint for /home/npr/camel-examples/examples/main/src/main/java/org/apache/camel/example/MyRouteBuilder.java l.27
2022-10-13 22:53:33.173 WARN [ForkJoinPool.commonPool-worker-5] [com.github.cameltooling.dap.internal.CamelDebugAdapterServer.setBreakpointsSync(CamelDebugAdapterServer.java:162)] - No active routes find in Camel context. Consequently, cannot set breakpoint for /home/npr/camel-examples/examples/main/src/main/java/org/apache/camel/example/MyRouteBuilder.java l.27
2022-10-13 23:18:29.390 ERROR [ForkJoinPool.commonPool-worker-19] [com.github.cameltooling.dap.internal.BacklogDebuggerConnectionManager.attach(BacklogDebuggerConnectionManager.java:133)] - Error trying to attach
java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 
	java.net.SocketTimeoutException: Read timed out]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:370) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[?:?]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:229) ~[?:?]
	at com.github.cameltooling.dap.internal.BacklogDebuggerConnectionManager.connect(BacklogDebuggerConnectionManager.java:159) ~[classes!/:?]
	at com.github.cameltooling.dap.internal.BacklogDebuggerConnectionManager.attach(BacklogDebuggerConnectionManager.java:113) ~[classes!/:?]
	at com.github.cameltooling.dap.internal.CamelDebugAdapterServer.lambda$attach$1(CamelDebugAdapterServer.java:106) ~[classes!/:?]
	at com.github.cameltooling.dap.internal.CamelDebugAdapterServer.lambda$runAsync$14(CamelDebugAdapterServer.java:352) ~[classes!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: javax.naming.CommunicationException
	at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:137) ~[?:?]
	at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:220) ~[?:?]
	at javax.naming.InitialContext.lookup(InitialContext.java:409) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1839) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1813) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:302) ~[?:?]
	... 13 more
Caused by: java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 
	java.net.SocketTimeoutException: Read timed out
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:300) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:196) ~[?:?]
	at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:343) ~[?:?]
	at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:116) ~[?:?]
	at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:133) ~[?:?]
	at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:220) ~[?:?]
	at javax.naming.InitialContext.lookup(InitialContext.java:409) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1839) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1813) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:302) ~[?:?]
	... 13 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:?]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:115) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:168) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:140) ~[?:?]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:252) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:271) ~[?:?]
	at java.io.DataInputStream.readByte(DataInputStream.java:270) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:239) ~[?:?]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:196) ~[?:?]
	at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:343) ~[?:?]
	at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:116) ~[?:?]
	at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:133) ~[?:?]
	at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:220) ~[?:?]
	at javax.naming.InitialContext.lookup(InitialContext.java:409) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1839) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1813) ~[?:?]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:302) ~[?:?]
	... 13 more
```

**Comment by Navyashree0923** [comment]
Some logs from the `Debugger : show Protocol` tab 
```
⟸ request/setBreakpoints(4) :: {'source': {'path': '/home/npr/camel-examples/examples/main/src/main/java/org/apache/camel/example/MyRouteBuilder.java'}, 'breakpoints': [SourceBreakpoint(line=27, column=None, condition=None, hitCondition=None, logMessage=None)], 'lines': [27]}
⟹ response/setBreakpoints(4) :: {'breakpoints': [{'verified': False, 'message': 'the breakpoint 0', 'source': {'path': '/home/npr/camel-examples/examples/main/src/main/java/org/apache/camel/example/MyRouteBuilder.java'}, 'line': 27}]}
⟸ process/stopped :: invalid literal for int() with base 10: b":41,346 Log4j2-TF-1-RollingFileManager-1 WARN Exception reported by action 'class org.apache.logging.log4j.core.appender.rolling.RollingFileManager$AsyncAction' java.nio.file.AccessDeniedException: 
```
Some lines from the `/tmp/log-dap-camel.log` 
```
bash-5.1$ cat /tmp/log-camel-dap.log 
2022-10-14 00:22:41.324 WARN [ForkJoinPool.commonPool-worker-5] [com.github.cameltooling.dap.internal.CamelDebugAdapterServer.setBreakpointsSync(CamelDebugAdapterServer.java:162)] - No active routes find in Camel context. Consequently, cannot set breakpoint for /home/npr/camel-examples/examples/main/src/main/java/org/apache/camel/example/MyRouteBuilder.java l.27
2022-10-14 00:27:31.811 WARN [ForkJoinPool.commonPool-worker-5] [com.github.cameltooling.dap.internal.CamelDebugAdapterServer.setBreakpointsSync(CamelDebugAdapterServer.java:162)] - No active routes find in Camel context. Consequently, cannot set breakpoint for /home/npr/camel-examples/examples/main/src/main/java/org/apache/camel/example/MyRouteBuilder.java l.27
2022-10-14 00:27:44.778 WARN [ForkJoinPool.commonPool-worker-5] [com.github.cameltooling.dap.internal.CamelDebugAdapterServer.setBreakpointsSync(CamelDebugAdapterServer.java:162)] - No active routes find in Camel context. Consequently, cannot set breakpoint for /home/npr/camel-examples/examples/main/src/main/java/org/apache/camel/example/MyRouteBuilder.java l.27
2022-10-14 00:28:22.486 WARN [ForkJoinPool.commonPool-worker-5] [com.github.cameltooling.dap.internal.CamelDebugAdapterServer.setBreakpointsSync(CamelDebugAdapterServer.java:162)] - No active routes find in Camel context. Consequently, cannot set breakpoint for /home/npr/camel-examples/examples/main/src/main/java/org/apache/camel/example/MyRouteBuilder.java l.27
```

**Comment by Navyashree0923** [comment]
Sorry my bad. As there was lot of other connections were active so it wasn't able to attach. Now after killing them I'm able to see the attach and I can see the following in `Debugger : show Protocol` : 
```
⟸ process/starting :: ['java', '-jar', '/home/npr/.config/sublime-text/Packages/Debugger/data/adapters/camel/extension/jars/camel-dap-server.jar']
⟸ process/started ::
⟸ request/initialize(1) :: {'clientID': 'sublime', 'clientName': 'Sublime Text', 'adapterID': 'camel', 'pathFormat': 'path', 'linesStartAt1': True, 'columnsStartAt1': True, 'supportsVariableType': True, 'supportsVariablePaging': False, 'supportsRunInTerminalRequest': True, 'supportsMemoryReferences': True, 'locale': 'en-us'}
⟹ response/initialize(1) :: {'supportsConfigurationDoneRequest': True, 'supportsConditionalBreakpoints': True, 'supportsSetVariable': True}
⟸ request/attach(2) :: {'name': 'Attach to Camel Debugger', 'port': 1099, 'request': 'attach', 'type': 'camel'}
⟹ event/initialized :: None
⟸ request/setBreakpoints(3) :: {'source': {'path': '/home/npr/camel-examples/examples/main/src/main/java/org/apache/camel/example/MyRouteBuilder.java'}, 'breakpoints': [SourceBreakpoint(line=27, column=None, condition=None, hitCondition=None, logMessage=None)], 'lines': [27]}
⟸ request/setExceptionBreakpoints(4) :: {'filters': [], 'filterOptions': []}
⟹ event/output :: {'category': 'telemetry', 'output': 'camel.dap.attach', 'data': {'name': 'camel.dap.attach', 'properties': {'success': True}}}
⟹ response/attach(2) :: None
⟸ request/threads(5) :: {}
⟸ process/stderr :: Oct 14, 2022 1:46:56 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.UnsupportedOperationException
	at org.eclipse.lsp4j.debug.services.IDebugProtocolServer.setExceptionBreakpoints(IDebugProtocolServer.java:293)
	... 16 more


⟾ response/setExceptionBreakpoints(4) :: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.UnsupportedOperationException
	at org.eclipse.lsp4j.debug.services.IDebugProtocolServer.setExceptionBreakpoints(IDebugProtocolServer.java:293)
	... 16 more

⟹ response/threads(5) :: {'threads': []}
⟹ response/setBreakpoints(3) :: {'breakpoints': [{'nodeId': 'log1', 'verified': True, 'message': 'the breakpoint 0', 'source': {'path': '/home/npr/camel-examples/examples/main/src/main/java/org/apache/camel/example/MyRouteBuilder.java'}, 'line': 27}]}
```
And also I can see it's not supporting serveral requests  because in the capabilities it's not saying that it's supporting setExceptionBreakpoints, Evaluation and setdataBreakpoints.

**Comment by Navyashree0923** [comment]
It is working now. I have missed clearing the cache and setting the breakpoints.
Thank you
