### ISSUE TITLE
Occasional drag assert

### ISSUE THREAD

**Issue by ihdavids** [daveleroy/sublime_debugger#188]
- Windows Machine
- Happens Periodically
- Debugger is not currently active.
- Not really a problem at the moment but felt you would want to know to resolve.

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 1105, in on_text_command
    res = callback(v, name, args)
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 162, in profiler
    return event_handler(*args)
  File "C:\Users\idavids\AppData\Roaming\Sublime Text\Packages\Debugger\modules\core\sublime.py", line 79, in on_text_command
    if (cmd == 'drag_select' or cmd == 'context_menu') and 'event' in args:
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 1105, in on_text_command
    res = callback(v, name, args)
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 162, in profiler
    return event_handler(*args)
  File "C:\Users\idavids\AppData\Roaming\Sublime Text\Packages\Debugger\start.py", line 192, in on_text_command
    if (cmd == 'drag_select' or cmd == 'context_menu') and 'event' in args:
TypeError: argument of type 'NoneType' is not iterable

**Comment by daveleroy** [comment]
Should be fixed in 0.8.2
