### ISSUE TITLE
C sharp 

### ISSUE THREAD

**Issue by patrickmungai** [daveleroy/sublime_debugger#234]

**Comment by photex** [comment]
Howdy,

I've forked the repo to attempt to add support for netcoredbg. I do not seem to be able to load the package when it isn't installed via package control unfortunately. 
I'm using Linux, are there any particular tricks for establishing a development environment for working on this package?

**Comment by photex** [comment]
```
reloading plugin SublimeDebugger.start
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 325, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 868, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/chipc/.config/sublime-text/Packages/SublimeDebugger/start.py", line 21, in <module>
    from .modules.command import CommandsRegistry, DebuggerExecCommand, DebuggerCommand, DebuggerInputCommand
  File "/home/chipc/.config/sublime-text/Packages/SublimeDebugger/modules/command.py", line 7, in <module>
    from .debugger import Debugger
  File "/home/chipc/.config/sublime-text/Packages/SublimeDebugger/modules/debugger.py", line 8, in <module>
    from .import dap
  File "/home/chipc/.config/sublime-text/Packages/SublimeDebugger/modules/dap/__init__.py", line 37, in <module>
    from .session import (
  File "/home/chipc/.config/sublime-text/Packages/SublimeDebugger/modules/dap/session.py", line 10, in <module>
    from .debugger import Console, ConsoleSessionBound, Debugger
ImportError: cannot import name 'ConsoleSessionBound' from 'SublimeDebugger.modules.dap.debugger' (/home/chipc/.config/sublime-text/Packages/SublimeDebugger/modules/dap/debugger.py)
```

**Comment by photex** [comment]
Ok, I had the package cloned as 'SublimeDebugger' but it needed to just be 'Debugger'.

Carrying on!

**Comment by photex** [comment]
No, I take that back. I still get this error. I just missed it in the console. The menu for the debugger package is populated, but everything is entirely greyed out.

Stepping back and realizing that maybe it isn't a problem with my environment, the traceback suggests that perhaps the class `ConsoleSessionBound` was not checked in?

**Comment by photex** [comment]
Ok, I'm going to just work from the 0.10.1 tag and then when something works, I can look into integrating with the changes since then.
There seem to be several things in-flight right now. :D
