### ISSUE TITLE
Unable to use Debugger for Python

### ISSUE THREAD

**Issue by Shinyhero36** [daveleroy/sublime_debugger#30]
Hi, I just installed this package for ST3 and i am running into an error.
What i have done so far:
- Debugger: Open in project
- Debugger: Install Adapters

and in the integrated console of ST3 i got this
`
An exception occured in the main_loop
Traceback (most recent call last):
  File "C:\Users\Responsable\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\core\core.py", line 25, in _exception_handler
    raise context['exception']
  File "C:\Users\Responsable\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "C:\Users\Responsable\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\commands\debugger.py", line 31, in run_main
    main.show()
  File "C:\Users\Responsable\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\debugger\debugger_interface.py", line 306, in show
    self.panel.show()
AttributeError: 'DebuggerInterface' object has no attribute 'panel'
`
#### So, do you know what i did wrong? Or what's going on?

**Comment by daveleroy** [comment]
You probably need to open it in a sublime text project. If you ignore the message it doesn't appear to say it again when you run Open in project a second time.

This should be cleaned up in the next version

**Comment by kapitanluffy** [comment]
I am having the similar issue too. this time it says `console_panel`

![image](https://user-images.githubusercontent.com/485799/65571256-aa7e4080-df96-11e9-83d3-ea7d2d50fcf5.png)

**Comment by daveleroy** [comment]
Should be fixed

> I am having the similar issue too. this time it says `console_panel`
> 
> ![image](https://user-images.githubusercontent.com/485799/65571256-aa7e4080-df96-11e9-83d3-ea7d2d50fcf5.png)

This should be fixed in the latest
