### ISSUE TITLE
Attach to remote python debugger in 3Ds Max

### ISSUE THREAD

**Issue by RockShea** [daveleroy/sublime_debugger#32]
Hello!

The potential of this plugin has me very excited, thank you very much for releasing it!
I am trying to setup remote python debugging with an instance of 3DsMax.
I have managed to get it working in VSCode as a test and am now trying to port this across to Sublime.
When I try to run the debugger, I get this error though:
![image](https://user-images.githubusercontent.com/14349787/63209971-02946e00-c0e0-11e9-9b82-46392abcf443.png)

Here is the full stack trace:
```
Starting process: ['node', 'C:\\Users\\shea.richardson\\AppData\\Roaming\\Sublime Text 3\\Packages/Debugger/data/debug_adapters/vscode-python/extension/out/client/debugger/debugAdapter/main.js']
An exception occured in the main_loop
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shea.richardson\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\core\core.py", line 25, in _exception_handler
    raise context['exception']
  File "C:\Users\shea.richardson\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "C:\Users\shea.richardson\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\core\core.py", line 110, in done
    result = task.result()
  File "C:\Users\shea.richardson\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 293, in result
    raise self._exception
  File "C:\Users\shea.richardson\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\shea.richardson\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\debugger\debugger.py", line 164, in _launch
    self.process = Process(adapter_configuration.command, on_stdout=None, on_stderr=self.log_info)
  File "C:\Users\shea.richardson\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\dap\transport.py", line 57, in __init__
    startupinfo=startupinfo)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

[WinError 2] The system cannot find the file specifiedTraceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shea.richardson\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\debugger\debugger.py", line 117, in launch
    yield from self.launching_async
  File "C:\Users\shea.richardson\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\shea.richardson\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\tasks.py", line 304, in _wakeup
    future.result()
  File "C:\Users\shea.richardson\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 293, in result
    raise self._exception
  File "C:\Users\shea.richardson\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\core\core.py", line 25, in _exception_handler
    raise context['exception']
  File "C:\Users\shea.richardson\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "C:\Users\shea.richardson\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\core\core.py", line 110, in done
    result = task.result()
  File "C:\Users\shea.richardson\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 293, in result
    raise self._exception
  File "C:\Users\shea.richardson\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\shea.richardson\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\debugger\debugger.py", line 164, in _launch
    self.process = Process(adapter_configuration.command, on_stdout=None, on_stderr=self.log_info)
  File "C:\Users\shea.richardson\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\dap\transport.py", line 57, in __init__
    startupinfo=startupinfo)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

and here is my config settings:
```
"debug.configurations":
[
	{
        "name": "Python: Remote Attach",
        "type": "python",
        "request": "attach",
        "port": 3000,
        "host": "localhost",
        "pathMappings":
        [
            {
                "localRoot": "C:/p4/Tools/Art/Python/Max/Development",
                "remoteRoot": "C:/p4/Tools/Art/Python/Max/Development"
            }
        ],
        // "pythonPath": "C:/Python37/python37.exe",
        // "debugOptions" :
        // {
    	// 	"RedirectOutput": true,
    	// }
    }
]
```
The main difference I could figure out between VSCode and Sublime is VSCode uses my local py37 install, but Sublime is trying to use it's own py33 version, hence the attempt to set "pythonPath".

Lastly, this is the code I am using to setup the remote server in Max's Python interpreter:
```
import ptvsd

ptvsd.enable_attach(address=('0.0.0.0', 3000))
```

Any assistance with this would be amazing as it is the last piece missing from the perfect Sublime setup!

**Comment by daveleroy** [comment]
I think this is just a case of a kind of shitty error message from pythons subprocess on windows. To start the adapter we tried to run ` ['node', 'C:\\Users\\shea.richardson\\AppData\\Roaming\\Sublime Text 3\\Packages/Debugger/data/debug_adapters/vscode-python/extension/out/client/debugger/debugAdapter/main.js']` pretty sure you either don't have node installed or its not in your path.

It would probably be nice to catch some of these errors  and add some additional context to them before barfing them into the debugger console

**Comment by RockShea** [comment]
Hah! It was exactly that, I hadn't installed node.
I am embarrassed that I did not spot that...
Thanks very much for the swift response.
