### ISSUE TITLE
frozen panel when debugging python code

### ISSUE THREAD

**Issue by randy3k** [daveleroy/sublime_debugger#36]
Sample program

```py
def f():
    x = 1
    return x

y = f()
print(y)
```

<img width="464" alt="Screen Shot 2019-09-06 at 5 12 30 PM" src="https://user-images.githubusercontent.com/1690993/64466970-892de100-d0c9-11e9-8ca5-27a328cbb58c.png">

<img width="666" alt="Screen Shot 2019-09-06 at 5 13 18 PM" src="https://user-images.githubusercontent.com/1690993/64467007-b8dce900-d0c9-11e9-962e-5ea78ad85535.png">

After toggling a breakpoint at line 2, all buttons in the panel are not responsive. (I also notice that the `node` process was not terminated after the window is closed at this point.)

Sublime Console shows the following error message
<details>

```
Starting process: ['node', '/Users/Randy/Dropbox/Sublime Text 3/Packages/Debugger/data/debug_adapters/vscode-python/extension/out/client/debugger/debugAdapter/main.js']
An exception occured in the main_loop
Traceback (most recent call last):
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/Debugger/modules/core/core.py", line 25, in _exception_handler
    raise context['exception']
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/Debugger/modules/libs/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/Debugger/modules/core/core.py", line 90, in wrapper
    return function(*args, **kwargs)
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/Debugger/modules/dap/client.py", line 393, in transport_message
    self.recieved_msg(msg)
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/Debugger/modules/core/core.py", line 90, in wrapper
    return function(*args, **kwargs)
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/Debugger/modules/dap/client.py", line 414, in recieved_msg
    future = self.pending_requests.pop(data['request_seq'])
KeyError: 1

Navigating to frame
Traceback (most recent call last):
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/Debugger/modules/ui/render.py", line 175, in run
    item.html = self._highlighter.syntax_highlight(item.text, item.language, inline=True)
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_code_highlight.py", line 267, in syntax_highlight
    self.set_view(src, 'text' if not lang else lang)
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/mdpopups/st3/mdpopups/st_code_highlight.py", line 233, in set_view
    keys = set(list(user_map.keys()) + list(lang_map.keys()))
AttributeError: 'NoneType' object has no attribute 'keys'
Settings were udpdated: reloading configuations
Settings were udpdated: reloading configuations
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1021, in run_
    return self.run(**args)
  File "/Applications/Sublime Text.app/Contents/MacOS/Packages/Default.sublime-package/settings.py", line 101, in run
AttributeError: 'NoneType' object has no attribute 'replace'
Unable to open /Users/Randy/Dropbox/Sublime Text 3/Packages/User/debugger.sublime-settings
```
</details>

I have an empty Debugger setting and my project settings have the following configuration

```
		"debug.configurations":
		[
			{
				"name": "Python Debug",
				"type": "python",
				"request": "launch",
				"program": "${folder}/test.py",
				"debugOptions" : {
					"RedirectOutput": true,
				}
			},
		]
```

macOS, python3 and Sublime Text 3208

**Comment by daveleroy** [comment]
Seems like an issue with mdpopups. If you run `import mdpopups; print(mdpopups.version());` what version does it say?

**Comment by randy3k** [comment]
I have the most updated 3.4.0

**Comment by randy3k** [comment]
I forgot why I put these two settings in my `Preferences.sublime-settings`, but it seems that they are causing the issue.

**Comment by randy3k** [comment]
But still, I got the following error even when I just start the debugger without the breakpoint.

```
Starting process: ['node', '/Users/Randy/Dropbox/Sublime Text 3/Packages/Debugger/data/debug_adapters/vscode-python/extension/out/client/debugger/debugAdapter/main.js']
An exception occured in the main_loop
Traceback (most recent call last):
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/Debugger/modules/core/core.py", line 25, in _exception_handler
    raise context['exception']
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/Debugger/modules/libs/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/Debugger/modules/core/core.py", line 90, in wrapper
    return function(*args, **kwargs)
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/Debugger/modules/dap/client.py", line 393, in transport_message
    self.recieved_msg(msg)
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/Debugger/modules/core/core.py", line 90, in wrapper
    return function(*args, **kwargs)
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/Debugger/modules/dap/client.py", line 414, in recieved_msg
    future = self.pending_requests.pop(data['request_seq'])
KeyError: 1

disposing Debugger
63823
63823
debug adapter process ended.
Traceback (most recent call last):
  File "/Users/Randy/Dropbox/Sublime Text 3/Packages/Debugger/modules/dap/transport.py", line 107, in close
    os.killpg(self.process.pid, signal.SIGTERM)
ProcessLookupError: [Errno 3] No such process

Debugger Transport: closed
Nothing to read from process, closing
```

**Comment by randy3k** [comment]
I dug into the code a little bit and realized that two messages with the same `request_seq` are received.

```
{'seq': 1, 'success': True, 'type': 'response', 'body': {'supportsGotoTargetsRequest': True, 'supportsExceptionOptions': True, 'supportsHitConditionalBreakpoints': True, 'supportsConfigurationDoneRequest': True, 'supportsCompletionsRequest': True, 'supportsSetVariable': True, 'supportsDelayedStackTraceLoading': True, 'supportsLogPoints': True, 'supportsConditionalBreakpoints': True, 'supportTerminateDebuggee': True, 'exceptionBreakpointFilters': [{'label': 'Raised Exceptions', 'default': False, 'filter': 'raised'}, {'label': 'Uncaught Exceptions', 'default': True, 'filter': 'uncaught'}], 'supportsValueFormattingOptions': True, 'supportsSetExpression': True, 'supportsEvaluateForHovers': True, 'supportsExceptionInfoRequest': True, 'supportsModulesRequest': True}, 'request_seq': 1, 'command': 'initialize'}

{'seq': 2, 'success': True, 'type': 'response', 'message': '', 'body': {'supportsGotoTargetsRequest': True, 'supportsHitConditionalBreakpoints': True, 'exceptionBreakpointFilters': [{'label': 'Raised Exceptions', 'default': False, 'filter': 'raised'}, {'label': 'Uncaught Exceptions', 'default': True, 'filter': 'uncaught'}], 'supportsSetVariable': True, 'supportsValueFormattingOptions': True, 'supportsConfigurationDoneRequest': True, 'supportsCompletionsRequest': True, 'supportsExceptionOptions': True, 'supportsDelayedStackTraceLoading': True, 'supportsConditionalBreakpoints': True, 'supportTerminateDebuggee': True, 'supportsExceptionInfoRequest': True, 'supportsSetExpression': True, 'supportsEvaluateForHovers': True, 'supportsDebuggerProperties': True, 'supportsLogPoints': True, 'supportsModulesRequest': True}, 'request_seq': 1, 'command': 'initialize'}
```

And poping `pending_requests` twice is causing the error.

**Comment by daveleroy** [comment]
Yeah but it seems unlikely to get fixed according to https://github.com/microsoft/vscode-python/issues/3762 they just don't care about implementing the protocol correctly as long as it works with vscode.

**Comment by daveleroy** [comment]
I ended up catching this exception and just adding a log that it happened a couple week backs I just haven't pushed my changes in awhile. It shouldn't actually cause any issues right now as far as I am aware through (besides the annoying exception being logged). I'll wrap the mdpopups syntax highlighting and catch and log any exceptions that one does actually break the debugger. if it happens.

**Comment by randy3k** [comment]
Thank you for your reply. I want to ask one more question while you are here - I am trying to evaluate a command via `Debugger: Run Command` at a breakpoint and I got the following error message: `Unable to find thread for evaluation`. Do you have any clue why it is the case?

**Comment by randy3k** [comment]
Maybe I am wrong, but it seems that it was caused by the value `frame` here: https://github.com/daveleroy/sublime_debugger/blob/388af75915de37128b294015f75345e8a62b457b/modules/debugger/debugger.py#L327

The variable `self.frame` is always empty in my tests.

**Comment by daveleroy** [comment]
Yes it should be `self.selected_frame`. This is broken in a few places and breaks all the evaluate requests so run command/hover don't work or don't work correctly depending on the adapter debugger. I've fixed it locally its just not pushed yet. I'll try to get all my changes in tomorrow.

**Comment by randy3k** [comment]
it seems the issues have been fixed on master.
