### ISSUE TITLE
UnboundLocalError: local variable 'platform' referenced before assignment

### ISSUE THREAD

**Issue by AmjadHD** [daveleroy/sublime_debugger#37]
I'm using the debugger with a python file, the debugger panel opens up but it's empty, when I look at the console I see this:
```
Debugger
start_event_loop
running main event loop
Starting up
reloading settings Packages/User/Preferences.sublime-settings
Package Control: No updated packages
An exception occured in the main_loop
Traceback (most recent call last):
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\core\core.py", line 25, in _exception_handler
    raise context['exception']
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\core\event.py", line 44, in _post
    h.callback(data)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\start.py", line 36, in on_view_activated
    DebuggerInterface.for_window(window, True)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\debugger\debugger_interface.py", line 125, in for_window
    main = DebuggerInterface(window)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\core\core.py", line 90, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\debugger\debugger_interface.py", line 273, in __init__
    self.load_configurations()
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\debugger\debugger_interface.py", line 354, in load_configurations
    configuration = Configuration.from_json(configuration_json)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\debugger\adapter_configuration.py", line 100, in from_json
    return Configuration(name, type, request, json)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\debugger\adapter_configuration.py", line 89, in __init__
    for item in platform.items():
UnboundLocalError: local variable 'platform' referenced before assignment
```
this is the contents of my `.sublime-project` file:
```json
{
	"folders":
	[
		{
			"path": "D:\\Amjad\\Python_project"
		}
	],
	"settings":
	{
		"debug.configurations":
		[
			{
			      "name": "Python Debug",
			      "type": "python",
			      "request": "launch",
			      "program": "${file}",
			},
		]
	}
}
```
OS: Windows 10
Debugger: latest master (e7992eb0d4e40862845f4b2df08c46b6964b89de)

**Comment by daveleroy** [comment]
This should be fixed now but you still won't be able to put "windows" specific stuff in your configuration (which you were not). What does running `import sys; print(sys.platform)` in the sublime console say?

**Comment by daveleroy** [comment]
> This should be fixed now but you still won't be able to put "windows" specific stuff in your configuration (which you were not). What does running `import sys; print(sys.platform)` in the sublime console say?

Figured it out. All fixes
