### ISSUE TITLE
Debugger not running

### ISSUE THREAD

**Issue by AmjadHD** [daveleroy/sublime_debugger#38]
I'm trying to run python debugger, but I can't run on any command
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33235928/65559400-d10e8e00-df3a-11e9-9fae-52917a668fd1.gif)
this is my project file
```json
{
	"folders":
	[
		{
			"path": "D:\\Amjad\\Python_project"
		}
	],
	"settings":
	{
		"debug.configurations":
		[
			{
			      "name": "Python Debug",
			      "type": "python",
			      "request": "launch",
			      "program": "${file}",
			},
		]
	}
}
```
log
```
Debugger
start_event_loop
running main event loop
Starting up
Creating a window: h
debugger.info Opened In Workspace: D:\Amjad\Sublime Projects
```
- click ▷
```
debugger.info Console cleared...
:debugger.error Add or select a configuration to begin debugging
```
- select "Python Debug" configuration
- click ▷
```
debugger.info Console cleared...
:Starting process: ['node', 'C:\\Users\\Lehdhili\\AppData\\Roaming\\Sublime Text 3\\Packages/Debugger/data/debug_adapters/vscode-python/extension/out/client/debugger/debugAdapter/main.js']
debugger.info starting debugger... 
:debugger.info (node:7500) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
- click on ||
```
:debugger.error debugger not running
:Traceback (most recent call last):
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\core\core.py", line 104, in done
    raise exception
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\debugger\debugger.py", line 331, in pause
    assert self.adapter, 'debugger not running'
AssertionError: debugger not running
```
I'm sure that python debugger is installed and used to run before a recent commit that I fail to remember which.

**Comment by daveleroy** [comment]
`$file` is probably empty did you save the file? If you give the python adapter an empty string the adapter starts but never begins debugging

**Comment by AmjadHD** [comment]
I already used the absolute path to the python file that i'm testing, but it didn't work.

**Comment by daveleroy** [comment]
If you have the code locally you can't change `should_log_info` to `True` in https://github.com/daveleroy/sublime_debugger/blob/master/modules/core/log.py (this should be toggle-able from the settings I just haven't got to it)

That will log all the commands being sent/received from the debug adapter. I suspect its some issue with the path being sent because that was the only way I could get the adapter to hang.

**Comment by AmjadHD** [comment]
I set `should_log_info` to `True`
```
:Starting process: ['node', 'C:\\Users\\Lehdhili\\AppData\\Roaming\\Sublime Text 3\\Packages/Debugger/data/debug_adapters/vscode-python/extension/out/client/debugger/debugAdapter/main.js']
debugger.info starting debugger... 
:<<  {"seq": 1, "command": "initialize", "arguments": {"supportsVariablePaging": false, "clientName": "Sublime Text", "supportsRunInTerminalRequest": true, "clientID": "sublime", "adapterID": "python", "columnsStartAt1": true, "linesStartAt1": true, "pathFormat": "path", "supportsVariableType": true, "locale": "en-us"}, "type": "request"}
debugger.info (node:5188) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

:>>  {"seq":1,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsExceptionInfoRequest":true,"supportsConfigurationDoneRequest":true,"supportsDelayedStackTraceLoading":true,"supportsConditionalBreakpoints":true,"supportsSetVariable":true,"supportsExceptionOptions":true,"supportsGotoTargetsRequest":true,"supportsEvaluateForHovers":true,"supportsModulesRequest":true,"supportsValueFormattingOptions":true,"supportsHitConditionalBreakpoints":true,"supportsSetExpression":true,"supportsLogPoints":true,"supportTerminateDebuggee":true,"supportsCompletionsRequest":true,"exceptionBreakpointFilters":[{"filter":"raised","label":"Raised Exceptions","default":false},{"filter":"uncaught","label":"Uncaught Exceptions","default":true}]}}
<<  {"seq": 2, "command": "launch", "arguments": {"name": "Python Debug", "type": "python", "program": "D:/Amjad/Python_project/main.py", "request": "launch"}, "type": "request"}
updating settings callback view
```
when clicking `||`
```
updating settings callback view
debugger.error debugger not running
:Traceback (most recent call last):
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\core\core.py", line 104, in done
    raise exception
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\debugger\debugger.py", line 331, in pause
    assert self.adapter, 'debugger not running'
AssertionError: debugger not running

updating settings callback view
```

**Comment by daveleroy** [comment]
The adapter never starts so if you hit pause its not going to pause and the pause button is probably grayed out.

I'm at a bit of a loss here

I have tried basically the same configuration on both Windows and Mac and it's working. You could try reinstalling the python adapter and making sure it works in VSCode. 

You could try reverting all the way back to 0.1.2 and see if it still works that might narrow things down if it is a regression

**Comment by AmjadHD** [comment]
when I looked at the python adapter, I found that the zip folder is corrupt, it wasn't downloaded successfully, so I downloaded it manually from https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/latest/vspackage
then I extracted, renamed and placed it in the debug _adapters folder, but that didn't solve it

```
:Starting process: ['node', 'C:/Users/Lehdhili/AppData/Roaming/Sublime Text 3/Packages/Debugger/data/debug_adapters/vscode-python/extension/out/client/debugger/debugAdapter/main.js']
debugger.info starting debugger... 
:debugger.info (node:6896) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

:An exception occured in the main_loop
Traceback (most recent call last):
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\core\core.py", line 25, in _exception_handler
    raise context['exception']
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\core\core.py", line 110, in done
    result = task.result()
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 293, in result
    raise self._exception
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\debugger\debugger.py", line 200, in _launch
    yield from adapter.Launch(configuration.all)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\dap\client.py", line 207, in Launch
    yield from self.send_request_asyc('launch', config)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\coroutines.py", line 213, in coro
    res = yield from res
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\tasks.py", line 304, in _wakeup
    future.result()
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 293, in result
    raise self._exception
Debugger.modules.dap.types.Error: spawn ENOMEM

spawn ENOMEMTraceback (most recent call last):
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\debugger\debugger.py", line 112, in launch
    yield from self.launching_async
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\tasks.py", line 304, in _wakeup
    future.result()
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 293, in result
    raise self._exception
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\core\core.py", line 25, in _exception_handler
    raise context['exception']
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\core\core.py", line 110, in done
    result = task.result()
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 293, in result
    raise self._exception
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\debugger\debugger.py", line 200, in _launch
    yield from adapter.Launch(configuration.all)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\dap\client.py", line 207, in Launch
    yield from self.send_request_asyc('launch', config)
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\coroutines.py", line 213, in coro
    res = yield from res
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\tasks.py", line 304, in _wakeup
    future.result()
  File "C:\Users\Lehdhili\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 293, in result
    raise self._exception
Debugger.modules.dap.types.Error: spawn ENOMEM

debugger.error ... an error occured, spawn ENOMEM
:debug adapter process ended.
```

**Comment by Namean** [comment]
{
	"folders":
	[
		{
			"path": "D:\\Amjad\\Python_project"
		}
	],
	"settings":
	{
		"debug.configurations": <-- looks like a typo, change "debug.configurations" to "debug_configurations"
		[
			{
			      "name": "Python Debug",
			      "type": "python",
			      "request": "launch",
			      "program": "${file}",
			},
		]
	}
}
