### ISSUE TITLE
Exception in main_loop

### ISSUE THREAD

**Issue by erazor-de** [daveleroy/sublime_debugger#45]
I'm trying to get your plugin up and running with gdb.

Used Versions:
Linux Fedora 27
Sublime Text Dev Build 3210
Debugger v0.1.8 with gdb/native-debug adapter installed
Node v10.15.3

My project configuration:
~~~
{
	"folders": [ { "path": "/home/stefan/workspace/test/c" } ],
	"settings": {
		"debug.configurations": [ {
			"type": "gdb",
			"request": "launch",
			"name": "Launch hello",
			"program": "/home/stefan/workspace/test/c/hello"
		} ]
	}
}
~~~
The mentioned executable exists and works.

My steps to reproduce:
Debugger/Open (Because I disabled automatic start)
Debugger/Start selecting "Launch hello"
Debugger/Start

The output in Sublime console:
~~~
debugger.info Console cleared...
:debugger.error Add or select a configuration to begin debugging
:Settings were udpdated: reloading configuations
Settings were udpdated: reloading configuations
debugger.info Console cleared...
:Starting process: ['node', '/home/stefan/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/native-debug/extension/out/src/gdb.js']
debugger.info starting debugger... 
:An exception occured in the main_loop
Traceback (most recent call last):
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/core/core.py", line 25, in _exception_handler
    raise context['exception']
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/core/core.py", line 110, in done
    result = task.result()
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/debugger/debugger.py", line 200, in _launch
    yield from adapter.Launch(configuration.all)
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/dap/client.py", line 207, in Launch
    yield from self.send_request_asyc('launch', config)
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/coroutines.py", line 213, in coro
    res = yield from res
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/futures.py", line 293, in result
    raise self._exception
Debugger.modules.dap.types.Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.isAbsolute (path.js:1136:5)
    at MI2.load (/home/stefan/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/native-debug/extension/out/src/backend/mi2/mi2.js:63:25)
    at GDBDebugSession.launchRequest (/home/stefan/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/native-debug/extension/out/src/gdb.js:65:29)
    at GDBDebugSession.dispatchRequest (/home/stefan/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/native-debug/extension/node_modules/vscode-debugadapter/lib/debugSession.js:341:22)
    at GDBDebugSession._handleData (/home/stefan/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/native-debug/extension/node_modules/vscode-debugadapter/lib/protocol.js:97:38)
    at Socket.inStream.on (/home/stefan/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/native-debug/extension/node_modules/vscode-debugadapter/lib/protocol.js:18:44)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.isAbsolute (path.js:1136:5)
    at MI2.load (/home/stefan/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/native-debug/extension/out/src/backend/mi2/mi2.js:63:25)
    at GDBDebugSession.launchRequest (/home/stefan/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/native-debug/extension/out/src/gdb.js:65:29)
    at GDBDebugSession.dispatchRequest (/home/stefan/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/native-debug/extension/node_modules/vscode-debugadapter/lib/debugSession.js:341:22)
    at GDBDebugSession._handleData (/home/stefan/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/native-debug/extension/node_modules/vscode-debugadapter/lib/protocol.js:97:38)
    at Socket.inStream.on (/home/stefan/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/native-debug/extension/node_modules/vscode-debugadapter/lib/protocol.js:18:44)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)Traceback (most recent call last):
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/debugger/debugger.py", line 112, in launch
    yield from self.launching_async
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/core/core.py", line 25, in _exception_handler
    raise context['exception']
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/core/core.py", line 110, in done
    result = task.result()
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/debugger/debugger.py", line 200, in _launch
    yield from adapter.Launch(configuration.all)
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/dap/client.py", line 207, in Launch
    yield from self.send_request_asyc('launch', config)
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/coroutines.py", line 213, in coro
    res = yield from res
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/home/stefan/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/futures.py", line 293, in result
    raise self._exception
Debugger.modules.dap.types.Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.isAbsolute (path.js:1136:5)
    at MI2.load (/home/stefan/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/native-debug/extension/out/src/backend/mi2/mi2.js:63:25)
    at GDBDebugSession.launchRequest (/home/stefan/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/native-debug/extension/out/src/gdb.js:65:29)
    at GDBDebugSession.dispatchRequest (/home/stefan/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/native-debug/extension/node_modules/vscode-debugadapter/lib/debugSession.js:341:22)
    at GDBDebugSession._handleData (/home/stefan/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/native-debug/extension/node_modules/vscode-debugadapter/lib/protocol.js:97:38)
    at Socket.inStream.on (/home/stefan/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/native-debug/extension/node_modules/vscode-debugadapter/lib/protocol.js:18:44)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)

debugger.error ... an error occured, TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.isAbsolute (path.js:1136:5)
    at MI2.load (/home/stefan/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/native-debug/extension/out/src/backend/mi2/mi2.js:63:25)
    at GDBDebugSession.launchRequest (/home/stefan/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/native-debug/extension/out/src/gdb.js:65:29)
    at GDBDebugSession.dispatchRequest (/home/stefan/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/native-debug/extension/node_modules/vscode-debugadapter/lib/debugSession.js:341:22)
    at GDBDebugSession._handleData (/home/stefan/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/native-debug/extension/node_modules/vscode-debugadapter/lib/protocol.js:97:38)
    at Socket.inStream.on (/home/stefan/.config/sublime-text-3/Packages/Debugger/data/debug_adapters/native-debug/extension/node_modules/vscode-debugadapter/lib/protocol.js:18:44)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
:debug adapter process ended.
~~~

Debugging works with lldb.
Any hints?

**Comment by daveleroy** [comment]
I don't think native-debug uses `program` in its configuration. It seems to use `target` to refer to the executable. 

https://github.com/WebFreak001/code-debug

**Comment by erazor-de** [comment]
That did the trick. Your "Default Debuggers" section in docs/setup.md does not contain a link for this adapter, so I googled for vscode gdb configuration instead. Maybe you want to add this.
Anyway, thanks for this project.
