### ISSUE TITLE
can not start on windows 7

### ISSUE THREAD

**Issue by huihui571** [daveleroy/sublime_debugger#70]
I use this plugin to debug python on windows7. After i had installed Adapters "vscode-python" and added configuration in the .sublime-project file, i got error when i click "start":
```
Traceback (most recent call last):
  File "D:\ProgramFiles\Sublime Text Build 3126 x64\Data\Packages\Debugger\modules\core\core.py", line 48, in done
    raise exception
  File "D:\ProgramFiles\Sublime Text Build 3126 x64\Data\Packages\Debugger\modules\libs\asyncio\tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "D:\ProgramFiles\Sublime Text Build 3126 x64\Data\Packages\Debugger\modules\debugger\debugger.py", line 382, in _on_play
    yield from self.debugger.launch(adapter_configuration, configuration_expanded, no_debug=no_debug)
  File "D:\ProgramFiles\Sublime Text Build 3126 x64\Data\Packages\Debugger\modules\debugger\debugger_session.py", line 121, in launch
    yield from self.launching_async
  File "D:\ProgramFiles\Sublime Text Build 3126 x64\Data\Packages\Debugger\modules\libs\asyncio\futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "D:\ProgramFiles\Sublime Text Build 3126 x64\Data\Packages\Debugger\modules\libs\asyncio\tasks.py", line 304, in _wakeup
    future.result()
  File "D:\ProgramFiles\Sublime Text Build 3126 x64\Data\Packages\Debugger\modules\libs\asyncio\futures.py", line 293, in result
    raise self._exception
  File "D:\ProgramFiles\Sublime Text Build 3126 x64\Data\Packages\Debugger\modules\core\sublime_event_loop.py", line 13, in __call__
    self.callback(*self.args)
  File "D:\ProgramFiles\Sublime Text Build 3126 x64\Data\Packages\Debugger\modules\core\core.py", line 54, in done
    result = task.result()
  File "D:\ProgramFiles\Sublime Text Build 3126 x64\Data\Packages\Debugger\modules\libs\asyncio\futures.py", line 293, in result
    raise self._exception
  File "D:\ProgramFiles\Sublime Text Build 3126 x64\Data\Packages\Debugger\modules\libs\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "D:\ProgramFiles\Sublime Text Build 3126 x64\Data\Packages\Debugger\modules\debugger\debugger_session.py", line 168, in _launch
    self.process = Process(adapter_configuration.command, on_stdout=None, on_stderr=self.info)
  File "D:\ProgramFiles\Sublime Text Build 3126 x64\Data\Packages\Debugger\modules\dap\transport.py", line 59, in __init__
    cwd = cwd)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```
That [WinError 2] means the system could not find the specified file, but i don't know which file it's referring to.  Is there some problems with python subprocess moudle or the sublime-debugger plugin?
btw: my sublime text is up to date, which is Version 3.3.2 Build 3211.
And this is my .sublime-project:
```
{
	"build_systems":
	[
		{
			"file_regex": "^[ ]*File \"(...*?)\", line ([0-9]*)",
			"name": "Anaconda Python Builder",
			"selector": "source.python",
			"shell_cmd": "\"d:\\ProgramFiles\\anaconda3\\envs\\pytorch36\\python.exe\" -u \"$file\""
		}
	],
	"folders":
	[
		{
			"path": "."
		}
	],
	"settings":
	{
		"debug.configurations":
		[
			{
			    "name": "Python: Current File (Integrated Terminal)",
			    "type": "python",
			    "request": "launch",
			    "program": "${file}",
			    "console": "integratedTerminal"
			},
			{
			    "name": "Python: Current File (External Terminal)",
			    "type": "python",
			    "request": "launch",
			    "program": "${file}",
			    "console": "externalTerminal"
			}

		]
	}
}
```

**Comment by daveleroy** [comment]
Pretty sure you just need `node` installed https://github.com/daveleroy/sublime_debugger/issues/57

Also for python it probably needs to be `node-v12.15.0` or less https://github.com/daveleroy/sublime_debugger/issues/55 unless the compatibility issue was fixed in vscode-python
