### ISSUE TITLE
 'DebuggerSession' object has no attribute 'capabilities'

### ISSUE THREAD

**Issue by sschuhmann** [daveleroy/sublime_debugger#74]
This error occures after running the debugger. 

ADAPTER: Python
OS: Linux
ST: 3

```
Debug Adapter process was terminated prematurely
Traceback (most recent call last):
  File "/home/sschuhmann/.config/sublime-text-3/Packages/Debugger/modules/core/core.py", line 48, in done
    raise exception
  File "/home/sschuhmann/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/sschuhmann/.config/sublime-text-3/Packages/Debugger/modules/debugger/debugger.py", line 382, in _on_play
    yield from self.debugger.launch(adapter_configuration, configuration_expanded, no_debug=no_debug)
  File "/home/sschuhmann/.config/sublime-text-3/Packages/Debugger/modules/debugger/debugger_session.py", line 121, in launch
    yield from self.launching_async
  File "/home/sschuhmann/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/home/sschuhmann/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/home/sschuhmann/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/home/sschuhmann/.config/sublime-text-3/Packages/Debugger/modules/core/sublime_event_loop.py", line 13, in __call__
    self.callback(*self.args)
  File "/home/sschuhmann/.config/sublime-text-3/Packages/Debugger/modules/core/core.py", line 54, in done
    result = task.result()
  File "/home/sschuhmann/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/home/sschuhmann/.config/sublime-text-3/Packages/Debugger/modules/libs/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/sschuhmann/.config/sublime-text-3/Packages/Debugger/modules/debugger/debugger_session.py", line 138, in _launch
    yield from self.stop()
  File "/home/sschuhmann/.config/sublime-text-3/Packages/Debugger/modules/debugger/debugger_session.py", line 338, in stop
    if self.capabilities.supportsTerminateRequest:
AttributeError: 'DebuggerSession' object has no attribute 'capabilities'
```

**Comment by mrecht** [comment]
Same problem here..

ADAPTER: lldb
OS: Win10 64bit
ST: 3

Project: Rust

`{
	"folders":
	[
		{
			"path": "."
		}
	],
	"settings":
	{
		"LSP":
		{
			"rust-analyzer":
			{
				"enabled": true
			}
		},
		"debug.configurations":
		[
			{
				"target": "${workspaceFolder}/target/debug/rust.exe", 
				"request": "launch", 
				"cwd": "${workspaceRoot}", 
				"valuesFormatting": "parseText", 
				"type": "lldb", 
				"name": "Launch Program"
			},
		]
	}
}
`

**Comment by cvlvxi** [comment]
Getting the same thing

**Comment by Prometheus1400** [comment]
Same issue.
v0.2.9
ADAPTER: lldb
OS: ubuntu 20.04 LTS
ST: 3
2 errors:
'Debugger session object has no attribute 'capabilities'
No threads to run command
