### ISSUE TITLE
0.2.6 No Longer Works with ST3?

### ISSUE THREAD

**Issue by munkybuttballs** [daveleroy/sublime_debugger#80]
Hello,

The latest update ( 0.2.6 ) won't work on ST3:
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\shea.richardson\AppData\Roaming\Sublime Text 3\Packages\Debugger\start.py", line 5, in <module>
    raise Error('This version of Debugger requires st4')
```
This makes life a bit difficult with ST4 not being released yet - is there some sort of version control via package control or do I need to manually install the last ST3 compatible version?

**Comment by daveleroy** [comment]
Sorry I accidentally tagged the release on the wrong branch. When package control picks up version 0.2.7 you can upgrade from package control.

**Comment by munkybuttballs** [comment]
Ah! No worries - cheers for the quick response and also, once again, thanks for the awesome plugin <3
