### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by mercurykd** [daveleroy/sublime_debugger#91]
![image](https://user-images.githubusercontent.com/30900414/93472353-90efaa80-f905-11ea-8a0b-bb1ab7366b06.png)
```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\core\core.py", line 48, in done
    raise exception
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\debugger\debugger.py", line 382, in _on_play
    yield from self.debugger.launch(adapter_configuration, configuration_expanded, no_debug=no_debug)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\debugger\debugger_session.py", line 121, in launch
    yield from self.launching_async
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\tasks.py", line 304, in _wakeup
    future.result()
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 293, in result
    raise self._exception
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\core\sublime_event_loop.py", line 13, in __call__
    self.callback(*self.args)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\core\core.py", line 54, in done
    result = task.result()
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\futures.py", line 293, in result
    raise self._exception
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\libs\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\debugger\debugger_session.py", line 168, in _launch
    self.process = Process(adapter_configuration.command, on_stdout=None, on_stderr=self.info)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\Debugger\modules\dap\transport.py", line 59, in __init__
    cwd = cwd)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] Не удается найти указанный файл
```

**Comment by mercurykd** [comment]
install node.js ...
